<a href="https://colab.research.google.com/github/coder-j-0090/Self_Study/blob/main/Python_DataAnalysis_ML/3_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#이차원 리스트 생성
data = [[1,2,3],[4,5,6],[7,8,9]]

a = np.array(data)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

파이썬이 데이터 타입을 안따진다. 느려진 대신 편하다. C를 이용해 함수 빠르게하려고 만든 라이브럴리가 numpy 가 만들어졌다.

In [ ]:
#data type
a.dtype

dtype('int64')

In [ ]:
#데이터 타입 수정
a = a.astype(np.float32)
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [ ]:
#값 찾기
a[0][1]

2.0

In [ ]:
#이차원 리스트인데 1차원처럼 하나만 쓰면 그 줄 자체가 나온다
a[0]

array([1., 2., 3.], dtype=float32)

In [ ]:
#1부터 10까지 2씩 커진다.
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
#reshape를 하면 모양을 바꾼다. (3,3) 하면 2차원배열로 3*3을 만든다
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### **reshape 기능은 중요하다!**

In [ ]:
#reshape 으로 3차원까지 만들면 reshape(몇차원배열인가, 세로 갯수값, 가로 갯수값)
#하나는 스칼라, 1줄은 벡터, 2차원은 매트릭스, 3차원 이상은 텐서

#1부터 13미만까지. 단, 모양을 맞출수 없으면 reshape 기능에 에러가 나온다. 12개 맞춰야 한다.
#np.arange(1,11).reshape(3,2,2)

np.arange(1,13).reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
#난. nan(not a number), na(not available : 잘못된 데이터), none
#난 에서 숫자가 들어가야 하는 칸에 숫자가 안들어가면 에러가 난다.
#백엽상에 숫자가 막 들어가야 하는데 온도 습도 이런걸 채워야 하는데 태풍이 와서 날라가서 자료가 없으면 빈칸이 된다.
#숫자가 있어야 되는데 빈거나 잘못된 데이터가 있을때 그런값들이 결손된 데이터다.(결측치)

#numpy 에서는 결측치가 에러를 일으키지 않도록 nan 이라는걸 만들어 놨다.
np.nan


nan

In [ ]:
np.nan*10

nan

In [ ]:
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [ ]:
a[0][1] = np.nan
#숫자로 들어가있는거 에러 안생기게 난을 만들어놨다.
a

array([[ 1., nan,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]], dtype=float32)

In [ ]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

위에 이미 있는데 이걸 왜 또했는지 모르겠다.
a[0][1] = np.nan  #정수에서는 nan 불가
a


In [ ]:
#linsapce 에서 1하고 10을 20칸으로 나눠라.
a = np.linspace(1,10,20)
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

# 연산

In [ ]:
data = np.arange(1,10).reshape(3,3)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#값이 두배가 된다. 일반 리스트 에서는 그냥 붙는다 넘파이에서는 행렬처럼 인식해서 같은 원소끼리 더해진다.
data+data

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
[1,2,3]+[1,2,3]

[1, 2, 3, 1, 2, 3]

In [ ]:
data+data


array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
data-data


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
data*data


array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [ ]:
data/data

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#행렬에서 dot는 행렬의 곱이다
np.dot(data, data)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

첫번쨰 사진은 경로의 갯수 구하기
매트릭스 좌표에서 도트프로덕트 크로스 프로덕트 벡터계산

내적은 효율성 외적은 회전이다.

a*b*cos세타면 같은 곱이라 효율적이다.

벡터의 내적과 외적


In [ ]:
np.dot(data,data)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
#데코레이터
data@data

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

# 차원


In [ ]:
#0차원 : 스칼라
a = np.array(1)
a



array(1)

In [ ]:
#바꿔주는게 reshape 이고 원래 모양은 찾기는 .shape
a.shape

()

In [ ]:
a.ndim

0

In [ ]:
#1차원 : 벡터
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
a.shape

(5,)

In [ ]:
a.ndim

1

In [ ]:
#2 차원 : 매트릭스
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.shape

(2, 3)

In [ ]:
a.ndim

2

In [ ]:
#3차원 : 3차원 이상의 다차원 행렬을 Tensor
a = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
a

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [ ]:
a.shape

(2, 3, 2)

# 매트릭스

In [ ]:
a = np.arange(12).reshape(2,3,2)

In [ ]:
#1차원으로 n(여기선 12)개의 칸을 다 1로 채우기. 소수점이 있으면 float 란 뜻이다.
b = np.ones(12)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
#3차원으로 ones 만들기
b = np.ones(12).reshape(2,3,2)
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
b = np.zeros(12).reshape(2,3,2)
b

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
d = np.eye(3) #단위행렬 : 대각선만 다 1이고 나머지는 다 0인 행렬을 단위행렬이라 부른다.
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
e = np.zeros([3,4])
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
e = np.zeros([3,4,2])
e

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
#0에 가까운 아주 작은 값을 집어넣는것을 empty 라고 말한다

f = np.empty([2,3])
f

array([[5.06621502e-310, 0.00000000e+000, 1.14365519e+243],
       [2.93487123e-130, 3.38983205e+208, 6.25593821e-310]])

In [ ]:
g = np.full((3,4),1000)
g

array([[1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000]])

In [ ]:
#3차원으로도 가능
g = np.full((3,4,2),556)
g

array([[[556, 556],
        [556, 556],
        [556, 556],
        [556, 556]],

       [[556, 556],
        [556, 556],
        [556, 556],
        [556, 556]],

       [[556, 556],
        [556, 556],
        [556, 556],
        [556, 556]]])

In [ ]:
#2부터 10까지 6개의 숫자로
h = np.linspace(2,10,6)
h

array([ 2. ,  3.6,  5.2,  6.8,  8.4, 10. ])

# 집계함수

In [ ]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
a[0][0] = 100
a

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [ ]:
a[0,1] = 1000
a

array([[ 100, 1000,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [ ]:
#평균찾기
np.mean(a)

114.4

In [ ]:
#중앙값
np.median(a)

6.5

In [ ]:
#표준편차
np.std(a)

296.5485457728633

In [ ]:
#편차 제곱의 평균은 분산
#편차(+,- 다 있다)

#분산
np.var(a)

87941.04

In [ ]:
#a에 있는 숫자들 다 더해준다
np.sum(a)

1144

In [ ]:
#그냥 sum(a) 를 쓰면 세로롤 더해진다

sum(a)

array([ 105, 1006,    9,   11,   13])

In [ ]:
a

array([[ 100, 1000,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [ ]:
np.sum(a, axis = 0)     #더할 축 지정

array([ 105, 1006,    9,   11,   13])

In [ ]:
np.sum(a, axis = 1)

array([1109,   35])

In [ ]:
np.max(a)

1000

In [ ]:
np.min(a)

2